Updated colors to support Mattermost themes
mattermost/mattermost-plugin-user-survey pull request #30
Opened 2024-05-24 08:01 UTC by harshilsharma63

#### Summary
Updated colors to support Mattermost themes

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-57748

2024-05-24 11:02 UTC, abhijit-singh commented on webapp/src/components/surveyPost/linearScaleQuestion/style.scss
>              background: rgba(var(--button-bg-rgb), 0.08);
background: rgba(var(--button-bg-rgb), 0.12);

2024-05-24 11:04 UTC, abhijit-singh requested changes
Thanks @harshilsharma63! I added a comment separately and rquesting one more change:
In `webapp/src/components/surveyPost/linearScaleQuestion/style.scss`, line 35, under  `&.disabled`, the color variable set might be incorrect. I think we can update it to `background: var(--center-channel-color-08);`

2024-06-04 03:59 UTC, harshilsharma63 commented on webapp/src/components/surveyPost/linearScaleQuestion/style.scss
>              background: rgba(var(--button-bg-rgb), 0.08);
Done!

2024-06-04 03:59 UTC, harshilsharma63 commented
> Thanks @harshilsharma63! I added a comment separately and rquesting one more change: In `webapp/src/components/surveyPost/linearScaleQuestion/style.scss`, line 35, under `&.disabled`, the color variable set might be incorrect. I think we can update it to `background: var(--center-channel-color-08);`

Done!

2024-06-06 12:05 UTC, harshilsharma63 commented
@abhijit-singh can please please try this out?

2024-06-06 13:27 UTC, abhijit-singh approved these changes
Looks good, thanks!

2024-06-07 05:49 UTC, Rajat-Dabade approved these changes

2024-06-07 06:06 UTC, merged